-- 1. Portfolio Summary (Based on 'Zone Config' Settings)
create table if not exists portfolio_summary (
  id bigint generated by default as identity primary key,
  total_capital numeric default 0, -- Initial Capital
  trade_size numeric default 0,    -- Trade Size per Entry
  number_of_zones int default 0,
  current_btc_price numeric,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Zones Configuration (Based on 'Zone Config' Table)
create table if not exists zones_config (
  id bigint generated by default as identity primary key,
  zone_number int,                 -- 'Zone'
  zone_name text not null,         -- 'Zone Name' (e.g., Zone 1, 88-90k)
  price_low numeric not null,      -- 'Price Low'
  price_high numeric not null,     -- 'Price High'
  zone_width numeric,              -- 'Zone Width'
  capital_allocated numeric,       -- 'Capital Allocated'
  entries_available int,           -- 'Entries Available'
  status text check (status in ('Active', 'Inactive', 'Reserve')) default 'Inactive',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Trade Log (Based on 'Trade Log' Table)
create table if not exists trade_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null, -- 'Date' + 'Time'
  order_type text check (order_type in ('BUY', 'SELL')) not null, -- 'Type'
  zone_name text,                  -- 'Zone' associated with the trade
  entry_price numeric not null,    -- 'Entry Price'
  quantity numeric not null,       -- 'Qty (BTC)'
  total_usdt numeric generated always as (entry_price * quantity) stored, -- 'Total (USDT)', or manual insert
  tp_price numeric,                -- 'TP Price'
  exit_price numeric,              -- 'Exit Price'
  exit_at timestamp with time zone, -- 'Exit Date'
  pnl_usdt numeric,                -- 'P/L (USDT)'
  pnl_percent numeric,             -- 'P/L %'
  status text check (status in ('OPEN', 'CLOSED', 'PENDING')) default 'OPEN', -- 'Status'
  notes text,                      -- 'Notes'
  matched_pair_id bigint references trade_log(id) -- Internal link to pair buy/sell
);

-- 4. Paper Trade Log (For Paper Trading Mode)
create table if not exists paper_trade_log (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  order_type text check (order_type in ('BUY', 'SELL')) not null,
  zone_name text,
  entry_price numeric not null,
  quantity numeric not null,
  total_usdt numeric, -- calculated in code: price * quantity
  fee_usdt numeric,   -- calculated in code: total_usdt * fee_rate
  tp_price numeric,
  exit_price numeric,
  exit_at timestamp with time zone,
  pnl_usdt numeric,
  pnl_percent numeric,
  status text check (status in ('OPEN', 'CLOSED', 'PENDING')) default 'OPEN',
  notes text,
  matched_pair_id bigint references paper_trade_log(id)
);

-- 5. Bot Settings (Required for Dashboard & Bot)
create table if not exists bot_settings (
  id bigint generated by default as identity primary key,
  rsi_limit int default 45,
  tp_usdt numeric default 200.0,
  grid_step_usdt numeric default 200.0,
  trade_cooldown int default 300,
  is_active boolean default true,
  trade_size_usdt numeric default 20.0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert default settings row if not exists
insert into bot_settings (id, rsi_limit, tp_usdt, grid_step_usdt, trade_cooldown, is_active, trade_size_usdt)
values (1, 45, 200.0, 200.0, 300, true, 20.0)
on conflict (id) do nothing;

-- 6. Baseline Prices (For Day 1 Reference)
-- Records the starting price when you begin trading an asset
create table if not exists baseline_prices (
  id bigint generated by default as identity primary key,
  symbol text not null unique,        -- e.g., 'BTCUSDT'
  baseline_price numeric not null,    -- Day 1 Price
  baseline_date timestamp with time zone default timezone('utc'::text, now()) not null,
  initial_capital numeric,            -- Starting Capital (USDT)
  notes text
);

-- 7. Portfolio Snapshots (For Equity Curve & Drawdown)
-- Records portfolio state at regular intervals
create table if not exists portfolio_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_time timestamp with time zone default timezone('utc'::text, now()) not null,
  symbol text default 'BTCUSDT',
  
  -- Market Data
  btc_price numeric not null,
  
  -- Equity Breakdown
  total_equity_usdt numeric not null,  -- Cash + Position Value
  realized_pnl numeric default 0,       -- Sum of closed trades P&L
  unrealized_pnl numeric default 0,     -- Mark-to-market of open trades
  total_fees_paid numeric default 0,
  
  -- Position Info
  open_trade_count int default 0,
  total_position_btc numeric default 0,
  total_position_usdt numeric default 0,
  
  -- Drawdown Metrics
  peak_equity numeric,                  -- Highest equity seen so far
  current_drawdown_pct numeric,         -- (Peak - Current) / Peak * 100
  max_drawdown_pct numeric,             -- Worst DD ever recorded
  
  -- Baseline Comparison
  baseline_price numeric,
  baseline_return_pct numeric           -- BTC change since baseline
);

-- Index for faster time-series queries
create index if not exists idx_snapshots_time on portfolio_snapshots(snapshot_time desc);
